apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # Ensures child apps are deleted when apps is deleted
spec:
  project: default
  source:
    repoURL: https://github.com/ivana-koceva/k8s-lab-gitops
    targetRevision: main
    path: apps         # ArgoCD watches this directory and its subfolders for Application manifests
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd  # Child Application CRDs live in the argocd namespace
  syncPolicy:
    automated:
      prune: true      # Removes resources from cluster if deleted from Git
      selfHeal: true   # Reverts manual cluster changes back to Git state