image:
  repository: ghcr.io/ivana-koceva/flask-demo
  digest: sha256:f53c3dce00206da838693bf829f861f551566a02f953a05ec222b28a2b155df0
service:
  port: 8080
ingress:
  host: flask-demo.local
securityContext:
  enabled: true
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001
livenessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 30
readinessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10
resources:
  requests:
    memory: 64Mi
    cpu: 50m
  limits:
    memory: 128Mi
    cpu: 100m
