image:
  repository: ghcr.io/ivana-koceva/flask-demo
  digest: sha256:191a9e5bbc922e6a0de6f8e9d657e806b16ce97902134f76ddbb0503f8d7ae82
service:
  port: 8080
ingress:
  host: flask-demo.local
securityContext:
  enabled: true
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001
livenessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 30
readinessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10
resources:
  requests:
    memory: 64Mi
    cpu: 50m
  limits:
    memory: 128Mi
    cpu: 100m
metrics:
  enabled: true
