image:
  repository: ghcr.io/ivana-koceva/flask-demo
  digest: sha256:f4f7192ec3401f81da9f82c0b82f75c070785b09f14aa5ccc9e757f2f70491eb
service:
  port: 8080
ingress:
  host: flask-demo.local
securityContext:
  enabled: true
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001
livenessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 30
readinessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10
resources:
  requests:
    memory: 64Mi
    cpu: 50m
  limits:
    memory: 128Mi
    cpu: 100m
